version: "3.8"
services:
  # pg_db:
  #   image: postgres:14-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD="strongPassword123!"
  #     - POSTGRES_DB=app
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db:/var/lib/postgresql/data
  message-broker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    # depends_on:
    #   - pg_db
volumes:
  db:
